#!/usr/bin/env bash
current_dir=$(pwd)
program_name=$(basename "$current_dir")
supervisor_config_fpath=$(printf "%s-supervisor.conf" "$program_name")

supervisor_config=$(cat <<EOF
[program:$program_name]
command=$current_dir/run.sh
directory=$current_dir
process_name=%(program_name)s
numprocs=1
user=$(whoami)

stopsignal=TERM
stopwaitsecs=10
stopasgroup=true

killasgroup=true

autostart=true
autorestart=true

redirect_stderr=true
redirect_stdout=true

stdout_logfile=$HOME/logs/supervisord/%(program_name)s-out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10

stderr_logfile=$HOME/logs/supervisord/%(program_name)s-err.log
stderr_logfile_maxbytes=50MB
EOF
)

echo "$supervisor_config" > $supervisor_config_fpath && \
echo "Generated $supervisor_config_fpath"
